### ISSUE TITLE
修复Office部署问题

### ISSUE THREAD

**Issue by Searchstars** [Stargazing-Studio/System-Init-Toolbox#1]
Office部署功能由于一个非常大的问题导致它在0.1BETA中被禁用。
目前我没有任何思路来解决这个问题。
报错大概是这样的：
![image](https://user-images.githubusercontent.com/47274115/147749611-49d0154d-6a46-4fdf-b330-7fbd228090cd.png)
我的网络连接正常，存储空间也充足。在另一台电脑上测试，也会出现一模一样的报错。
即使不通过此程序运行Office部署工具，直接通过cmd运行甚至直接双击打开，都会出现此错误。
希望各位能提供一些思路，帮助我们尽快修复此问题。

**Comment by madobeichika** [comment]
先卸载已安装的Office
https://aka.ms/SaRA-officeUninstallFromPC

**Comment by Searchstars** [comment]
可是我并没有安装任何版本的Office：
![image](https://user-images.githubusercontent.com/47274115/147825260-a4e104b0-c4da-4163-b20e-e0c922206477.png)
你看，没有Word。
![image](https://user-images.githubusercontent.com/47274115/147825274-2e5ef5f8-3c71-4c1c-8c6a-fd3f5c2c56ad.png)
你看，也没有Microsoft Office文件夹。
![image](https://user-images.githubusercontent.com/47274115/147825291-b1a5839c-c94a-46d3-bf51-ae6aa4c451e0.png)
仅仅有一个系统自带的网页版Office罢了。
而且话说，这个网页版Office，也不会带来太大影响吧？

**Comment by madobeichika** [comment]
> 可是我并没有安装任何版本的Office： ![image](https://user-images.githubusercontent.com/47274115/147825260-a4e104b0-c4da-4163-b20e-e0c922206477.png) 你看，没有Word。 ![image](https://user-images.githubusercontent.com/47274115/147825274-2e5ef5f8-3c71-4c1c-8c6a-fd3f5c2c56ad.png) 你看，也没有Microsoft Office文件夹。 ![image](https://user-images.githubusercontent.com/47274115/147825291-b1a5839c-c94a-46d3-bf51-ae6aa4c451e0.png) 仅仅有一个系统自带的网页版Office罢了。 而且话说，这个网页版Office，也不会带来太大影响吧？

建议都删了

**Comment by Searchstars** [comment]
> > 可是我并没有安装任何版本的Office： ![image](https://user-images.githubusercontent.com/47274115/147825260-a4e104b0-c4da-4163-b20e-e0c922206477.png) 你看，没有Word。 ![image](https://user-images.githubusercontent.com/47274115/147825274-2e5ef5f8-3c71-4c1c-8c6a-fd3f5c2c56ad.png) 你看，也没有Microsoft Office文件夹。 ![image](https://user-images.githubusercontent.com/47274115/147825291-b1a5839c-c94a-46d3-bf51-ae6aa4c451e0.png) 仅仅有一个系统自带的网页版Office罢了。 而且话说，这个网页版Office，也不会带来太大影响吧？
> 
> 建议都删了

已经删了，但仍然报错0-2054

**Comment by Searchstars** [comment]
Office部署问题现已修复。
问题原因：
1.使用了损坏的Setup.exe导致无限报错。
2.代码中会调用cmd命令，但调用的命令并没有使用双引号，导致xml路径一旦出现空格就会部署失败。

**Comment by Searchstars** [comment]
当然，还有：
3.我的宽带太拉了无法测试，毕竟某农工商校园网
