### ISSUE TITLE
AMD显卡驱动下载问题

### ISSUE THREAD

**Issue by Searchstars** [Stargazing-Studio/System-Init-Toolbox#3]
你看看人家老黄，是吧，wget都能下载，啊，自然c#程序也能下，是吧。
AMD，你看看你，啊，wget都下不了，非得用浏览器下，请求头改成浏览器的都不行，啊，这点东西都要防，害，真的太逊了辣！
所以还有什么解决办法呢...？
我们一起想一想吧......

**Comment by madobeichika** [comment]
加个referer

**Comment by madobeichika** [comment]
#4

**Comment by Searchstars** [comment]
已在0.4BETA中解决
